#  Assignment 5

This assignment covers material on matrices, norms, condition numbers and eigensystems. The assignment is due by 5pm on Friday the 17th of April.

The breakdown of the marks is as follows:

Question 0 - [1 mark]  
Question 1 - [7 marks]  
Questino 2 - [6 marks]  
Question 3 - [7 marks]  
Question 4 - [9 marks]  

# Question 0

You should have saved this notebook to your ACM20030-Assignments folder. Now:
- commit the notebook to your local repository
- push the changes to the GitHub

In [1]:
import numpy as np
from numpy import linalg as la
np.set_printoptions(linewidth=200)  # This stops line wrapping of larger matrices

# Question 1 - practice manipulating arrays

This questions asks you write a few functions for manipulating arrays of data

## Q1 a

Write a function that checks if a given $n\times n$ matrix is symmetric. Use only loops and `.shape` function from numpy (do not use any other special numpy functions).

In [2]:
def SymmetryTest(A):
    n = A.shape[0]
    if(A.shape[1]!=n):
        return 0
    for i in range(0,n):
        for j in range(i+1,n): #Checks every number below the diagonal(the diagonal itself doesn't matter)
            if(A[i][j] != A[j][i]):
                return 0
    return 1

Test your function on the two matrices below

In [3]:
A = np.random.rand(5,5)
SymMatrix = (A + A.T)/2
def testresult(i):
    if(i==0):
        return "not symmetric"
    else:
        return "symmetric"
print("The matrix A is",testresult(SymmetryTest(A)))
print("The matrix SymMatrix is",testresult(SymmetryTest(SymMatrix)))

The matrix A is not symmetric
The matrix SymMatrix is symmetric


## Q1 b

Write a function to transpose a general $n\times n$ matrix. Do this by writing loops and not using any special functions like `np.transpose()`, `A.T`, or any functions from any other library.

In [4]:
def Transpose(A):
    n = A.shape[0]
    B = np.empty([n,n])
    for i in range(0,n):
        for j in range(0,n):
            B[i][j] = A[j][i]
    return B

Check your code by transposing the below random matrix and checking that $A^T \neq A$ and $(A^T)^T - A = 0$

In [5]:
A = np.random.rand(6,6)
print("A =",A,"\nA.T =\n",Transpose(A),"\n=> A.T is not equal to A\n")
print("A.T.T - A =\n",Transpose(Transpose(A))-A,"= 0")

A = [[0.67993894 0.5667665  0.38933673 0.46020267 0.25362835 0.91774069]
 [0.10774435 0.44934827 0.84978447 0.24613595 0.84333907 0.4291883 ]
 [0.71863188 0.75351908 0.25748018 0.24787271 0.0206246  0.74072372]
 [0.32255151 0.40386148 0.82483328 0.64262932 0.90047358 0.28299347]
 [0.69574033 0.48061144 0.69866805 0.22873116 0.43035016 0.91011174]
 [0.55659602 0.0589295  0.76992664 0.75081488 0.60228161 0.96191799]] 
A.T =
 [[0.67993894 0.10774435 0.71863188 0.32255151 0.69574033 0.55659602]
 [0.5667665  0.44934827 0.75351908 0.40386148 0.48061144 0.0589295 ]
 [0.38933673 0.84978447 0.25748018 0.82483328 0.69866805 0.76992664]
 [0.46020267 0.24613595 0.24787271 0.64262932 0.22873116 0.75081488]
 [0.25362835 0.84333907 0.0206246  0.90047358 0.43035016 0.60228161]
 [0.91774069 0.4291883  0.74072372 0.28299347 0.91011174 0.96191799]] 
=> A.T is not equal to A

A.T.T - A =
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0.

## Q1c

Write a function that finds the maximum entry in a matrix (where the matrix does not need to be square). Do this by writing loops and not using any special functions like `np.max` or any functions from any other library.

In [6]:
def Maximum(A):
    Max = A[0][0]
    for i in range(0,A.shape[0]):
        for j in range(0,A.shape[1]):
            if(Max < A[i][j]):
                Max = A[i][j]
    return Max

Check your result by comparing to `np.max(A)` for the below random matrix

In [7]:
A = np.random.rand(4,5)
print("np.max(A) = ",np.max(A))
print("Maximum(A) =",Maximum(A))

np.max(A) =  0.9955521402125576
Maximum(A) = 0.9955521402125576


# Question 2:  matrix norms

In the lectures we focused on the $L^2$-norm. We also briefly mentioned the $L^1$ and $L^\infty$ norm. Let's look at calculating those as well for a general $m\times n$ matrix.

# Q2a

The $L^1$ norm is given by

$$ \lVert A \rVert_1 = \max_j \sum^m_{i=1} |a_{ij}| $$

i.e., it is the max of the sums of the absolute values of each column. Write a function that computes the $L^1$-norm using only loops. The function should use no special numpy functions except `np.abs()`.

In [8]:
def L1(A):
    MaxSum = 0
    for j in range(0,A.shape[1]):
        Sum = 0
        for i in range(0,A.shape[0]):
            Sum += np.abs(A[i][j])
        if(MaxSum < Sum):
            MaxSum = Sum
    return MaxSum

Check your result against NumPy's `la.norm(A,1)` function for the following random matrix

In [9]:
A = np.random.rand(3,4)
print("la.norm(A,1) = ",la.norm(A,1))
print("L1(A) =",L1(A))

la.norm(A,1) =  2.09093768613607
L1(A) = 2.09093768613607


## Q2b

The $L^\infty$ norm is given by 

$$\lVert A \rVert_\infty = \max_i \sum_{j=1}^n |a_{ij}|$$

i.e., it is the max of the sums of the absolute values of each row. Write a function that computes the $L^\infty$-norm using only loops and no special numpy functions.

In [10]:
def Linf(A):
    MaxSum = 0
    for i in range(0,A.shape[0]):
        Sum = 0
        for j in range(0,A.shape[1]):
            Sum += np.abs(A[i][j])
        if(MaxSum < Sum):
            MaxSum = Sum
    return MaxSum

Check your result against NumPy's `la.norm(A,np.inf)` function for the following random matrix

In [11]:
A = np.random.rand(3,4)
print("la.norm(A,np.inf) = ",la.norm(A,np.inf))
print("Linf(A) =",Linf(A))

la.norm(A,np.inf) =  3.0603619205056867
Linf(A) = 3.0603619205056867


# Question 3: ill-conditions systems of equations

In this question you can use any of NumPy's functions.

## Q3a

Which of the following three matrices, $A1, A2, A3$, are ill-conditioned. State the reason for your conclusion.

In [12]:
A1 = np.array([[0.988746460106, 0.351486109477, 0.024911477532, 0.384039749683],
       [0.282104657306, 0.239884151775, 0.36170151991 , 0.903082266861],
       [0.59333290915 , 0.637178863968, 0.241229214635, 0.685595037901],
       [0.013591747828, 0.917926970364, 0.458689093885, 0.157821121254]])

A2 = np.array([[ 2.852416473483e-01,  3.803483118694e-01,  2.697704226632e-01,  6.810611849029e-01],
       [ 6.622827828376e-01,  6.447943415836e-01,  4.387842058829e-01,  1.530575702376e+00],
       [ 3.672130860703e-01,  8.309522079704e-01,  9.975487474007e-01,  5.678296337101e-01],
       [ 4.036490000599e-01,  6.865978225967e-06,  8.788095913773e-01, -7.150472427928e-02]])

A3 = np.array([[0.131923621844, 0.245316154195, 0.732362341613, 0.957047891764],
       [0.91290446184 , 0.512312007959, 0.391938831444, 0.092509684772],
       [0.648708523652, 0.608576675797, 0.576773587276, 0.065385122929],
       [0.502955480393, 0.084082960221, 0.659487390444, 0.662958739412]])

In [13]:
print("A1 is well-conditioned as its condition number is",la.cond(A1))
print("A2 is ill-conditioned as its condition number is",la.cond(A2))
print("A2 is well-conditioned as its condition number is",la.cond(A3))

A1 is well-conditioned as its condition number is 21.552466488381846
A2 is ill-conditioned as its condition number is 13334936994.070848
A2 is well-conditioned as its condition number is 15.12244969941062


# Q3b

With $b = [1,2,3,4]$ and $\delta b = [0.1,0,0,0]$ for $A2$ and $A3$ calculate the percentage change in $x$ due to a small change in $b$, i.e., calculate 

$$100\times\frac{\lVert \delta x_i\rVert_2}{\lVert x_i \rVert_2}\quad\text{and}\quad 100\times\frac{\lVert \delta b\rVert_2}{\lVert b \rVert_2}$$

where $(x_i+\delta x_i)  = A_i^{-1}(b+\delta b)$ and $i\in\{2,3\}$.

In [14]:
def L2(x):
    Sum = 0
    for i in x:
        Sum += i**2
    return(np.sqrt(Sum))
b = [1,2,3,4]
db = [0.1,0,0,0]
print("Change in b =",round(100*L2(db)/L2(b),2),"%")
lA2b = L2(np.dot(la.inv(A2), b))
lA2db= L2(np.dot(la.inv(A2),db))
lA3b = L2(np.dot(la.inv(A3), b))
lA3db= L2(np.dot(la.inv(A3),db))
print("Change in x for A2 =",round(100*lA2db/lA2b,2),"%")
print("Change in x for A3 =",round(100*lA3db/lA3b,2),"%")

Change in b = 1.83 %
Change in x for A2 = 512.62 %
Change in x for A3 = 2.17 %


Which system of equations is more sensitive to small changes in $b$? How could you have guessed this from the answer to the Q3a?

In [15]:
# Answer here
#A2 is more sensitive to small changes, this could also be inferred from its large condition number

# Question 4: eigensystems

In this question we look at finding eigenvalues and eigenvectors

## Q4a

You may use any of NumPy's functions for this sub-question.

Find the eigenvalues and eigenvectors for the below matrix. Print out the eigenvalues sorted by descending value and explicitly show that eigenvalues/eigenvector pairs satisfy $Ax = \lambda x$.

In [16]:
A = np.array([[1,4,5],[4,5,4],[6,7,9]])

In [17]:
(values,vectors) = la.eig(A)
print("The eigenvlaues are",round(values[0],3),",",round(values[2],3),"and",round(values[1],3))
for i in range(0,3):
    print("A * vectors["+str(i)+"] =",np.dot(A,vectors[:,i]),"=",round(values[i],2),"* vectors["+str(i)+"] =",np.dot(values[i],vectors[:,i]))


The eigenvlaues are 15.786 , 1.266 and -2.052
A * vectors[0] = [ -6.1962015   -7.01266016 -12.71289871] = 15.79 * vectors[0] = [ -6.1962015   -7.01266016 -12.71289871]
A * vectors[1] = [ 1.83806756 -0.74382849 -0.52676368] = -2.05 * vectors[1] = [ 1.83806756 -0.74382849 -0.52676368]
A * vectors[2] = [ 0.12430099 -0.98053324  0.79103825] = 1.27 * vectors[2] = [ 0.12430099 -0.98053324  0.79103825]


# Q4b

Without using NumPy's `la.eig()` (or similar functions), find the 4 eigenvalues and eigenvectors of the following matrix. Hint: Use the power method for the max eigenvalue (given below in `MaxEigenvalue`), the power method applied to the inverse for the smallest eigenvalue, and apply Hotelling's deflation twice to find the second and third eigenvalues/eigenvectors.

In [18]:
A = np.array([[1.935052353404, 0.887037260957, 1.534235483277, 1.370691224125],
       [0.887037260957, 0.81275989158 , 0.610238622918, 0.999150521052],
       [1.534235483277, 0.610238622918, 1.562260333538, 1.007843062517],
       [1.370691224125, 0.999150521052, 1.007843062517, 1.813258814483]])

In [19]:
def MaxEigenvalue(A, err):
    (m,n) = A.shape
    if(m != n):
        print("Matrix must be square")
        return
    x = np.random.rand(m)
    lam = 0.1
    lamprev = 1
    while np.abs(1-lam/lamprev) > err:
        p = np.dot(A,x)
        lamprev = lam
        lam = np.max(p)
        x = p/lam
    x = x/la.norm(x)
    return (lam,x)

In [20]:
values = np.zeros(4)
vectors = np.empty([4,4])
def Areduce(matrix,value,vector):
    Areduce = np.empty(A.shape)
    uuT = np.empty([len(vector),len(vector)])
    for i in range(0,A.shape[0]):
        for j in range(0,A.shape[1]):
            uuT[i][j] = vector[i]*vector[j]
            Areduce[i][j] = matrix[i][j] - value*uuT[i][j]
    return Areduce


(values[0],vectors[:,0]) = MaxEigenvalue(A,10**-6)
u1 = vectors[:,0]
Areduce1 = Areduce(A,values[0],u1)
(values[1],vectors[:,1]) = MaxEigenvalue(Areduce1,10**-6)
u2 = vectors[:,1]
Areduce2 = Areduce(Areduce1,values[1],u2)
(values[2],vectors[:,2]) = MaxEigenvalue(Areduce2,10**-6)
(values[3],vectors[:,3]) = (1/MaxEigenvalue(la.inv(A),10**-8)[0],MaxEigenvalue(la.inv(A),10**-8)[1])
print("The eigenvalues are qeual to",round(values[0],3),round(values[1],3),round(values[2],3),round(values[3],3))
print("The eigenvectors are equal to the columns of:\n",vectors)         

The eigenvalues are qeual to 4.915 0.851 0.215 0.143
The eigenvectors are equal to the columns of:
 [[ 0.59947639 -0.30724091  0.38116635 -0.63319961]
 [ 0.33318808  0.38944451  0.67390089  0.53214539]
 [ 0.49528108 -0.58292481 -0.34000313  0.54707608]
 [ 0.53320766  0.64353296 -0.53382364 -0.1287917 ]]


Check your answers against Numpy's results from `la.eig(A)`

In [21]:
(values,vectors) = la.eig(A) 
print("The eigenvalues are qeual to",round(values[0],3),round(values[1],3),round(values[2],3),round(values[3],3))
print("The eigenvectors are equal to the columns of:\n",vectors)
#Aside from the eigenvalues/vectors being in a different order, 
#and some of the vectors being out by a factor of -1, these results match well with the code above

The eigenvalues are qeual to 4.915 0.851 0.143 0.215
The eigenvectors are equal to the columns of:
 [[ 0.59947641  0.30724064 -0.63319959 -0.3811686 ]
 [ 0.33318806 -0.3894447   0.53214542 -0.67389895]
 [ 0.49528112  0.58292464  0.54707607  0.34000478]
 [ 0.53320761 -0.64353313 -0.12879172  0.53382343]]
