#  Assignment 5

This assignment covers material on matrices, norms, condition numbers and eigensystems. The assignment is due by 5pm on Friday the 17th of April.

The breakdown of the marks is as follows:

Question 0 - [1 mark]  
Question 1 - [7 marks]  
Questino 2 - [6 marks]  
Question 3 - [7 marks]  
Question 4 - [9 marks]  

# Question 0

You should have saved this notebook to your ACM20030-Assignments folder. Now:
- commit the notebook to your local repository
- push the changes to the GitHub

In [2]:
import numpy as np
from numpy import linalg as la
np.set_printoptions(linewidth=200)  # This stops line wrapping of larger matrices

# Question 1 - practice manipulating arrays

This questions asks you write a few functions for manipulating arrays of data

## Q1 a

Write a function that checks if a given $n\times n$ matrix is symmetric. Use only loops and `.shape` function from numpy (do not use any other special numpy functions).

In [3]:
def SymmetryTest(A):
    n = A.shape[0]
    if(A.shape[1]!=n):
        return 0
    for i in range(0,n):
        for j in range(i+1,n): #Checks every number below the diagonal(the diagonal itself doesn't matter)
            if(A[i][j] != A[j][i]):
                return 0
    return 1

Test your function on the two matrices below

In [5]:
A = np.random.rand(5,5)
SymMatrix = (A + A.T)/2
def testresult(i):
    if(i==0):
        return "not symmetric"
    else:
        return "symmetric"
print("The matrix A is",testresult(SymmetryTest(A)))
print("The matrix SymMatrix is",testresult(SymmetryTest(SymMatrix)))

The matrix A is not symmetric
The matrix SymMatrix is symmetric


## Q1 b

Write a function to transpose a general $n\times n$ matrix. Do this by writing loops and not using any special functions like `np.transpose()`, `A.T`, or any functions from any other library.

In [14]:
def Transpose(A):
    n = A.shape[0]
    B = np.empty([n,n])
    for i in range(0,n):
        for j in range(0,n):
            B[i][j] = A[j][i]
    return B

Check your code by transposing the below random matrix and checking that $A^T \neq A$ and $(A^T)^T - A = 0$

In [37]:
A = np.random.rand(6,6)
print("A =",A,"\nA.T =",Transpose(A),"=> A.T is not equal to A")
print("For example, A[0,1] =",A[0,1],"while A.T[0,1] =",Transpose(A)[0,1])
print("A.T.T - A =",Transpose(Transpose(A))-A,"= 0")

A = [[0.13480859 0.20941445 0.86758202 0.46407576 0.39212711 0.51195779]
 [0.91698672 0.65966822 0.47449347 0.84165713 0.10309138 0.65235764]
 [0.8372151  0.27018903 0.71113462 0.79355382 0.97735955 0.01168411]
 [0.91119138 0.27378443 0.35707589 0.70057212 0.60420393 0.10917041]
 [0.33612822 0.17483737 0.27128263 0.51424567 0.42149671 0.72845945]
 [0.57078052 0.86266259 0.13155844 0.4234995  0.42653494 0.19297938]] 
A.T = [[0.13480859 0.91698672 0.8372151  0.91119138 0.33612822 0.57078052]
 [0.20941445 0.65966822 0.27018903 0.27378443 0.17483737 0.86266259]
 [0.86758202 0.47449347 0.71113462 0.35707589 0.27128263 0.13155844]
 [0.46407576 0.84165713 0.79355382 0.70057212 0.51424567 0.4234995 ]
 [0.39212711 0.10309138 0.97735955 0.60420393 0.42149671 0.42653494]
 [0.51195779 0.65235764 0.01168411 0.10917041 0.72845945 0.19297938]] => A.T is not equal to A
For example, A[0,1] = 0.20941444767758055 while A.T[0,1] = 0.9169867223588966
A.T.T - A = [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [

## Q1c

Write a function that finds the maximum entry in a matrix (where the matrix does not need to be square). Do this by writing loops and not using any special functions like `np.max` or any functions from any other library.

In [38]:
def Maximum(A):
    Max = A[0][0]
    for i in range(0,A.shape[0]):
        for j in range(0,A.shape[1]):
            if(Max < A[i][j]):
                Max = A[i][j]
    return Max

Check your result by comparing to `np.max(A)` for the below random matrix

In [44]:
A = np.random.rand(4,5)
print("np.max(A) = ",np.max(A))
print("Maximum(A) =",Maximum(A))

np.max(A) =  0.8357541158890464
Maximum(A) = 0.8357541158890464


# Question 2:  matrix norms

In the lectures we focused on the $L^2$-norm. We also briefly mentioned the $L^1$ and $L^\infty$ norm. Let's look at calculating those as well for a general $m\times n$ matrix.

# Q2a

The $L^1$ norm is given by

$$ \lVert A \rVert_1 = \max_j \sum^m_{i=1} |a_{ij}| $$

i.e., it is the max of the sums of the absolute values of each column. Write a function that computes the $L^1$-norm using only loops. The function should use no special numpy functions except `np.abs()`.

In [73]:
def L1(A):
    MaxSum = 0
    for j in range(0,A.shape[1]):
        Sum = 0
        for i in range(0,A.shape[0]):
            Sum += np.abs(A[i][j])
        if(MaxSum < Sum):
            MaxSum = Sum
    return MaxSum

Check your result against NumPy's `la.norm(A,1)` function for the following random matrix

In [74]:
A = np.random.rand(3,4)
print("la.norm(A,1) = ",la.norm(A,1))
print("L1(A) =",L1(A))

la.norm(A,1) =  2.6693810924669688
L1(A) = 2.6693810924669688


## Q2b

The $L^\infty$ norm is given by 

$$\lVert A \rVert_\infty = \max_i \sum_{j=1}^n |a_{ij}|$$

i.e., it is the max of the sums of the absolute values of each row. Write a function that computes the $L^\infty$-norm using only loops and no special numpy functions.

In [75]:
def Linf(A):
    MaxSum = 0
    for i in range(0,A.shape[0]):
        Sum = 0
        for j in range(0,A.shape[1]):
            Sum += np.abs(A[i][j])
        if(MaxSum < Sum):
            MaxSum = Sum
    return MaxSum

Check your result against NumPy's `la.norm(A,np.inf)` function for the following random matrix

In [83]:
A = np.random.rand(3,4)
print("la.norm(A,np.inf) = ",la.norm(A,np.inf))
print("Linf(A) =",Linf(A))

la.norm(A,np.inf) =  1.7502118402854183
Linf(A) = 1.7502118402854183


# Question 3: ill-conditions systems of equations

In this question you can use any of NumPy's functions.

## Q3a

Which of the following three matrices, $A1, A2, A3$, are ill-conditioned. State the reason for your conclusion.

In [85]:
A1 = np.array([[0.988746460106, 0.351486109477, 0.024911477532, 0.384039749683],
       [0.282104657306, 0.239884151775, 0.36170151991 , 0.903082266861],
       [0.59333290915 , 0.637178863968, 0.241229214635, 0.685595037901],
       [0.013591747828, 0.917926970364, 0.458689093885, 0.157821121254]])

A2 = np.array([[ 2.852416473483e-01,  3.803483118694e-01,  2.697704226632e-01,  6.810611849029e-01],
       [ 6.622827828376e-01,  6.447943415836e-01,  4.387842058829e-01,  1.530575702376e+00],
       [ 3.672130860703e-01,  8.309522079704e-01,  9.975487474007e-01,  5.678296337101e-01],
       [ 4.036490000599e-01,  6.865978225967e-06,  8.788095913773e-01, -7.150472427928e-02]])

A3 = np.array([[0.131923621844, 0.245316154195, 0.732362341613, 0.957047891764],
       [0.91290446184 , 0.512312007959, 0.391938831444, 0.092509684772],
       [0.648708523652, 0.608576675797, 0.576773587276, 0.065385122929],
       [0.502955480393, 0.084082960221, 0.659487390444, 0.662958739412]])

In [99]:
print("A1 is ill-conditioned as",la.eig(A1.T@A1)[0],la.det(A1),la.inv(A1))
print("A2 is ill-conditioned as its condition number is",la.cond(A2))
print("A3 is ill-conditioned as",la.eig(A3.T@A3)[0],la.det(A3),la.inv(A3))

A1 is ill-conditioned as [3.53851005 0.74962438 0.40138078 0.00761775] 0.09005826852913093 [[ 2.09776876  0.63043493 -2.12169354  0.50475731]
 [-1.49173934 -1.91136986  3.39922014 -0.19944749]
 [ 3.49368804  3.84881234 -7.72101366  3.01594234]
 [-1.6583406  -0.1234246   2.85225727 -1.31263902]]
A2 is ill-conditioned as its condition number is 13334936994.070848
A3 is ill-conditioned as [3.9195836  1.01874455 0.09504718 0.0171394 ] -0.08065291344382224 [[-0.62576811  1.60524543 -1.20942492  0.79864351]
 [ 2.06785772  1.41738796  0.05698576 -3.18856496]
 [-1.69308062 -3.54198708  3.30322793  2.61259907]
 [ 1.89669001  2.12584972 -2.37562569 -1.29201749]]


# Q3b

With $b = [1,2,3,4]$ and $\delta b = [0.1,0,0,0]$ for $A2$ and $A3$ calculate the percentage change in $x$ due to a small change in $b$, i.e., calculate 

$$100\times\frac{\lVert \delta x_i\rVert_2}{\lVert x_i \rVert_2}\quad\text{and}\quad 100\times\frac{\lVert \delta b\rVert_2}{\lVert b \rVert_2}$$

where $(x_i+\delta x_i)  = A_i^{-1}(b+\delta b)$ and $i\in\{2,3\}$.

Which system of equations is more sensitive to small changes in $b$? How could you have guessed this from the answer to the Q3a?

In [10]:
# Answer here
#

# Question 4: eigensystems

In this question we look at finding eigenvalues and eigenvectors

## Q4a

You may use any of NumPy's functions for this sub-question.

Find the eigenvalues and eigenvectors for the below matrix. Print out the eigenvalues sorted by descending value and explicitly show that eigenvalues/eigenvector pairs satisfy $Ax = \lambda x$.

In [50]:
A = np.array([[1,4,5],[4,5,4],[6,7,9]])

# Q4b

Without using NumPy's `la.eig()` (or similar functions), find the 4 eigenvalues and eigenvectors of the following matrix. Hint: Use the power method for the max eigenvalue (given below in `MaxEigenvalue`), the power method applied to the inverse for the smallest eigenvalue, and apply Hotelling's deflation twice to find the second and third eigenvalues/eigenvectors.

In [52]:
A = np.array([[1.935052353404, 0.887037260957, 1.534235483277, 1.370691224125],
       [0.887037260957, 0.81275989158 , 0.610238622918, 0.999150521052],
       [1.534235483277, 0.610238622918, 1.562260333538, 1.007843062517],
       [1.370691224125, 0.999150521052, 1.007843062517, 1.813258814483]])

In [53]:
def MaxEigenvalue(A, err):
    (m,n) = A.shape
    if(m != n):
        print("Matrix must be square")
        return
    x = np.random.rand(m)
    
    lam = 0.1
    lamprev = 1
    while np.abs(1-lam/lamprev) > err:
        p = np.dot(A,x)
        lamprev = lam
        lam = np.max(p)
        x = p/lam
        
    x = x/la.norm(x)
    return (lam,x)

Check your answers against Numpy's results from `la.eig(A)`